import type { Metadata } from "next";
import { Quicksand } from 'next/font/google'
import "./globals.css";

const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['300','400','500','600','700'], // todos os pesos disponíveis
  variable: '--font-quicksand',
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${quicksand.variable} antialiased h-full bg-gray-100`}
      >
        {children}
      </body>
    </html>
  );
}
